apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grayfile

resources:
  - namespace.yaml
  - gateway.yaml
  - ext-proc.yaml
  - envoy.yaml
  - management-ui.yaml
  - observability.yaml
  - ingress.yaml

images:
  - name: registry.example.com/grayfile/gateway
    newTag: 0.1.0
  - name: registry.example.com/grayfile/ext-proc
    newTag: 0.1.0
  - name: registry.example.com/grayfile/management-ui
    newTag: 0.1.0

configMapGenerator:
  - name: envoy-config
    files:
      - envoy.yaml=config/envoy/envoy.yaml
  - name: prometheus-config
    files:
      - prometheus.yml=config/prometheus/prometheus.yml
  - name: grafana-datasources
    files:
      - datasource.yml=config/grafana/provisioning/datasources/datasource.yml
  - name: grafana-dashboards-provider
    files:
      - dashboard.yml=config/grafana/provisioning/dashboards/dashboard.yml
  - name: grafana-dashboard-grayfile-overview
    files:
      - grayfile-overview.json=config/grafana/dashboards/grayfile-overview.json

generatorOptions:
  disableNameSuffixHash: true
