CREATE TABLE IF NOT EXISTS audit_log (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(255) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255) NOT NULL,
    payload_json CLOB NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prev_hash VARCHAR(255),
    event_hash VARCHAR(255) NOT NULL,
    signature VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_occurred_at
    ON audit_log (occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_log_entity
    ON audit_log (entity_type, entity_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS audit_export_state (
    id SMALLINT PRIMARY KEY,
    last_exported_event_id BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO audit_export_state (id, last_exported_event_id) KEY (id)
VALUES (1, 0);
